### ISSUE TITLE
Adopt open source license

### ISSUE THREAD

**Issue by psmoot** [dell/opentelemetry-cli#132]
**Is your feature request related to a problem? Please describe.**
Adopt an open source license for opentelemetry-cli

**Describe the solution you'd like**
Adopt an open source license. Replace the existing LICENSE file with an open source license. I don't particularly care whether this is MIT, BSD, GPL, Mozilla, or some other license.

**Describe alternatives you've considered**
None.

**Additional context**
I'd be interested in contributing to this repo but it is licensed as Dell property. As I am no longer a Dell employee, I don't feel comfortable contributing.

**Comment by msarahan** [comment]
The [existing LICENSE file](https://github.com/dell/opentelemetry-cli/blob/main/LICENSE) is MIT. The copyright notice is standard for the MIT license: https://opensource.org/license/mit

**Comment by psmoot** [comment]
Oh. My bad, I didn't realize that's what the text says. Thank you for clarifying.

Would it be reasonable to say "This is the MIT license" somewhere? I know the source document you linked doesn't require it but perhaps that would avoid future confusion.

**Comment by msarahan** [comment]
It's in the GitHub UI:

![2024-11-22_12-25](https://github.com/user-attachments/assets/ac708fc9-f54f-4042-8ea4-002584bab1f2)

I haven't seen many repos explicitly describe their license in README files.
